name: SOAT application build and SonarCloud quality check

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install tox

    - name: Build application
      run: |
        tox -e py
        sed -i "s/<source>\/home\/runner\/work\/soat-order-status\/soat-order-status\/app\/src\/core\/usecase<\/source>/<source>\/github\/workspace\/app\/src\/core\/usecase<\/source>/g" /home/runner/work/soat-order-status/soat-order-status/coverage.xml
        cat coverage.xml | grep source
        
        
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
